infra-geo-ouverte/igo2

src/app/pages/navigator/navigator.component.ts, src/app/shared/collapsible/collapsible.component.ts, src/app/shared/flex/flex.component.ts, src/app/shared/flex/flex.ts, src/app/shared/flex/index.ts
WARNING in ./src/app/shared/collapsible/collapsible.component.ts
32:79-88 "export 'FlexState' was not found in '../flex/flex.component'
No warning. See this issue for more details: https://github.com/angular/angular-cli/issues/2034
```
[ ] Yes
[X] No
```
=> fix(flex): fix warning "export FlexState was not found"

src/app/context/context-list-item/context-list-item.component.html, src/app/pages/navigator/navigator.component.html, src/app/pages/navigator/navigator.component.ts
- No tool history ketp and go back simly unselect any tool
- Tool history is kept and go back selected the previous tool
```
[ ] Yes
[x] No
```
=> feat(tool): Keep tool history and go back functionnality

src/app/map/layer-form/layer-form.component.ts, src/app/map/layer-list-item/layer-list-item.component.html, src/app/map/layer-list/layer-list.component.spec.ts, src/app/map/layer-list/layer-list.component.ts, src/app/map/map-editor/map-editor.component.spec.ts, src/app/map/map.module.ts, src/app/map/map/map.component.spec.ts, src/app/map/map/map.component.ts, src/app/map/shared/capabilities.service.spec.ts, src/app/map/shared/capabilities.service.ts, src/app/map/shared/layer.service.spec.ts, src/app/map/shared/layer.service.ts, src/app/map/shared/layers/layer-osm.ts, src/app/map/shared/layers/layer-tile.ts, src/app/map/shared/layers/layer-vector.ts, src/app/map/shared/layers/layer-wms.ts, src/app/map/shared/layers/layer-wmts.ts, src/app/map/shared/layers/layer-xyz.ts, src/app/map/shared/layers/layer.ts, src/app/map/shared/map.ts, src/app/store/reducers/layers.reducer.ts
- The olLayer is not created in the layer constructor
- GetCapabilities options are out of sync between the olLayer and the layer itself
- GetCapabilities may break the layer order because of it's async nature
- Capabilities stuff are a bit spread out between the layer.service and the layers themselves
- The title in the capabilites was always overwritten by the title in the context
- The olLayer is created in the layer constructor
- GetCapabilities are synced with the layer options (they're the same)
- Layer order is based on the zIndex and is kept consistent
- Capabilities service contains capabilities stuff
- The title is …
=> Layer refactor

package.json, src/app/analysis/analysis.module.ts, src/app/analysis/time-analyser-form/time-analyser-form.component.html, src/app/analysis/time-analyser-form/time-analyser-form.component.spec.ts, src/app/analysis/time-analyser-form/time-analyser-form.component.styl, src/app/analysis/time-analyser-form/time-analyser-form.component.ts, src/app/analysis/time-analyser-list-item/time-analyser-list-item.component.spec.ts, src/app/analysis/time-analyser-list-item/time-analyser-list-item.component.styl, src/app/analysis/time-analyser-list/time-analyser-list.component.spec.ts, src/app/analysis/time-analyser/time-analyser.component.spec.ts, src/contexts/embacle.json
- No datepicker in the time analyser because material doesn't support it yet
- New library (ng2) with a datepicker. These datepickers will probably be replaced and the lib removed when material releases it's own datepicker.
```
[ ] Yes
[x] No
```
=> feat(time analyser): add temporary datepickers to the time analyser

.angular-cli.json, package.json
Manual operation to create gh-pages
Auto-generated gh-pages
=> chore(ghpages): add auto-generated ghpages

.travis.yml, package.json, proxy.conf.json, src/app/app.module.ts, src/app/pages/portal/portal.component.ts, src/contexts/embacle.json
=> fix(travis): fix npm cache with npm5 and node v8.0

src/app/pages/portal/portal.component.ts
1- If we change of context, the defined tool in url was coming back again and again.
2- If timeout is set to 1ms, seem to be not enough.
1- Only open tool once,
2- higher delay.
```
[ ] Yes
[x] No
```
=> Load tool once, not at every context change.

src/contexts/_default.json, src/environments/environment.ts
Visible property adjustment in default context so it can't have two active baselayers.
=> fix(context): visible property adjustment (default context)

src/app/pages/portal/portal.component.ts
igo-backdrop is now shown when media is Tablet and Orientation is Portrait. 
github issue igo2 #315
=> ui(toast-panel): igo-backdrop shown when tablet and portrait (igo#315)

src/app/pages/portal/portal.component.html
Refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/550
=> Refer to IGO2-lib PR # 550

src/app/pages/portal/toast-panel/toast-panel.component.html, src/app/pages/portal/toast-panel/toast-panel.component.ts, src/locale/en.json, src/locale/fr.json
To zoom on current feature, user must navigate into a contextual menu in the toast-panel header.
Access to a zoom button inside the toast-panel header 
+ 
various tooltips
```
[ ] Yes
[x] No
```
=> feat(toast-panel) add zoom button on selected feature

src/app/pages/portal/toast-panel/toast-panel.component.scss
- Fix zoom menu icon (toast-panel) for IE11
=> fix(toast-panel): zoom menu icon IE fix

src/polyfills.ts
- Polyfill to allow export (flatMap is not supported in IE)
- Still an error message when trying to export (maybe IE is really incompatible...)
=> fix(export): export with IE

docs/config_json.rst, src/app/pages/portal/portal.component.html, src/app/pages/portal/portal.component.ts, src/app/pages/portal/toast-panel/toast-panel.component.ts, src/config/config.json
For query results -- Small line or polygon visible at a small scale were pratically invisible despite the highlight style
Adding a pin point, based on the ration  feature extent/ view extent for line and poly. 
When zooming in
, if the previous ratio become under a threshold, the pin is removed.
It is possible the configurate the status of this feature. To disable the feature, under the app config.json, you can turn of this feature this way: 
```
"hasFeatureEmphasisOnSelection": false,
```
```
[ ] Yes
[ ] No
```
If this PR contains a breaking change, please …
=> Add a emphasis feature for line and polygon too deep in view

docs/config_json.rst, src/app/pages/portal/welcome-window/welcome-window.component.html, src/app/pages/portal/welcome-window/welcome-window.component.ts, src/locale/en.json, src/locale/fr.json
No way to specify application specific content to the welcome windows.
Allow to use title, description, version, releaseDate into the welcomeWindows.
{{title}} come from the app config
{{description}} come from the app config
{{version}} come from the app config OR the lib version ([igo2-lib](https://github.com/infra-geo-ouverte/igo2-lib/blob/next/packages/core/src/lib/config/version.ts))  
{{releaseDate}} come from the app config OR the lib version ([igo2-lib](https://github.com/infra-geo-ouverte/igo2-lib/blob/next/packages/core/src/lib/config/version.ts))  
```
[ …
```
=> welcomeWindow - provide parameters to the welcome message.

docs/config_json.rst, src/app/pages/portal/portal.component.html, src/app/pages/portal/portal.component.scss, src/app/pages/portal/portal.component.ts, src/app/pages/portal/portal.theming.scss, src/config/config.json
https://github.com/infra-geo-ouverte/igo2/issues/486
a new config is add:
"menuButtonReverseColor": true,
when is true the menu button color is reverse for theming color
```
[ ] Yes
[ x] No
```
=> feat(portal) add config reverse menu button color 

src/app/pages/portal/portal.component.ts
- When on mobile and search result is selected, close the sidenav
- If not, map is too little to see clearly that something happened
=> fix(sidenav): close sidenav when result is selected in mobile

docs/properties.rst
- Compléter la documentation sur les différents formats de coordonnées soutenues par la recherche de coordonnées
=> docs(icherche-reverse): add docs for coord format

docs/config_json.rst, docs/properties.rst, src/environments/environment.ts
- Add docs for catalog's forced properties and abstract
- Add case figure for forced properties catalog (wms, wmts and ArcgisREST)
=> Docs and case figure

docs/properties.rst, src/contexts/variousFormats.json
=> (Docs) vector dataSource doc et exemple avec donnéeQuébec dans démo

docs/config_json.rst, src/app/pages/portal/portal.component.ts, src/contexts/layerSync.json, src/contexts/ogcFilters.json, src/contexts/testExport.json, src/contexts/variousFormats.json, src/contexts/workspace.json, src/environments/environment.ts
lié a 
https://github.com/infra-geo-ouverte/igo2-lib/pull/815
=> Share arcgis

src/environments/environment.github.ts, src/environments/environment.prod.ts, src/environments/environment.ts
- Allow training guide url in depot config
- Input = string array
- If training guides are not defined in depot config, there must be context config url if you want to retrieve it from a specific profil
=> feat(trainingGuide): allow training guide in depot config

docs/properties.rst
- Fix selector type attribute -> not necessary anymore with the auto detection of the selector type
- Fix json code block
=> fix(ogc-filter docs): fix seletorType attribute

docs/properties.rst
=> docs(properties): add maxLayerZoomExtent property to map

src/app/pages/portal/portal.component.html, src/app/pages/portal/portal.component.scss, src/app/pages/portal/portal.component.ts, src/app/pages/portal/portal.theming.scss, src/config/interactiveTour.json, src/style/theme.scss
- Menu button style do not display correctly since release 1.9.0 due to theming breaking change
- Menu button component is now implemented in igo2-lib to allow the actual theming structure to display button style correctly
```
[ ] Yes
[X] No
```
=> refactor(menu-button): change menu button component to library

docs/url_control.rst, src/app/pages/portal/portal.component.ts
Permet de zoomer à l'étendue désirée à l'ouverture de la carte. Les coordonnées sont en latitude longitude, selon la logique suivante [minx, miny, maxx, maxy]. Elles seront converties selon la projection de la carte.
La problématique vient du fait que le zoom et le center (par url) ne permettent pas d'obtenir le même résultat, par mobile, tablette ou bureau. 
Params :
- zoomExtent=
Exemple:
- https://infra-geo-ouverte.github.io/igo2/?zoomExtent=-72,60,-71,61
```
[ ] Yes
[ ] No
```
If this PR contains a breaking change, please describe the impact and migration path …
=> feat(portal): allow to control the initial extent by url

src/app/app.component.ts
with safari <=11 swipe on map doesn't work.
now safari <=11 and IE <=11 is detect as oldBrowser and a notice message is show
```
[ ] Yes
[x ] No
```
=> Feat(app-component.ts) old browser add safari<=11 and IE11

src/app/pages/portal/portal.component.html, src/assets/images/styles/fire-hydrant.svg, src/assets/mapboxStyleExample-vectortile.json, src/contexts/_base.json, src/contexts/_contexts.json, src/contexts/variousFormats.json, src/contexts/variousStyles.json
Refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/951
=> feat(demo): add style context demo.

src/contexts/testExport.json
Layers in the Test export context do not have associated ids, causing problems when testing the Import/Export tool
Ids have been added to the layers to correct the problem.
```
[ ] Yes
[ ] No
```
=> fix(contexts): added ids for Test export context

src/locale/en.json, src/locale/fr.json
Some typos were present in some translation strings
Typos are fixed.
```
[ ] Yes
[ ] No
```
=> fix(locale): fixed errors in Google strings

docs/_tables/fr/properties/filter/igoOgcFilterDuring.csv, docs/config_json.rst, docs/properties.rst, src/contexts/ogcFilters.json
fix demo pour contexte filtre attributaire: 
- Changement des titres de couche
- Retrait de filtre avancé pour couches ayant des boutons
fix docs:
- filtre OGC: modif exemple temps année, fix coquille sur param restrictStep. Ajout précision sur fonctionnement badge pour filtre temporel. Ajout de précisions sur optionsFromCapabilities:true VS filtreOGC 
- storedQuery, change exemple MTQ call stored query 110 -> 116
- message add new info sur la librairie ngx-toaster
=> fix(demo+docs) - ogc-filter-time

src/app/pages/portal/portal.component.ts
https://github.com/infra-geo-ouverte/igo2/issues/721
the query infopanel close when the context change
```
[ ] Yes
[ x] No
```
=> feat(portal) Close query InfoPanel on context change

docs/_tables/fr/properties/map-view.csv, src/app/pages/portal/portal.component.html, src/app/pages/portal/portal.component.scss, src/app/pages/portal/portal.component.ts, src/config/config.json, src/config/interactiveTour.json, src/contexts/_base.json, src/contexts/_contexts.json, src/contexts/homeExtent.json, src/locale/en.json, src/locale/fr.json
The button to return to the home extent of the map is missing.
The user can clic the button on the map to return to the home extent. The home extent can be defined (in config.json) for each portal and can be different from the initial extent. 
```
[ ] Yes
[x] No
```
=> feat(portal): new homeExtent button

src/app/pages/portal/portal.component.ts
https://github.com/infra-geo-ouverte/igo2/issues/768
The workspace.entityStore is now clear on context change
```
[ ] Yes
[x ] No
```
=> fix(portal) Wks clear entityStore on context change

docs/_tables/fr/properties/edition.csv, src/app/pages/portal/portal.component.html
add button is always available
add button can now be disabled by default edition config
```
[ ] Yes
[X] No
=> feat(edition): add button is now configurable

docs/_tables/fr/properties/layersLinkProperties.csv, docs/properties.rst, src/contexts/_base.json, src/contexts/layerSync.json
Bidirectionnal property can be set to true or false when setting sync layers
Bidirectionnal property has been removed as of now, every sync layer are bidirectionnal
https://github.com/infra-geo-ouverte/igo2-lib/pull/1107
```
[X] Yes
[ ] No
```
Remove bidirectionnal property from linked layers configuration
=> refactor(layerSync): remove bidirectionnal property

src/app/pages/portal/portal.component.ts
On use of the map sharing tool a layer coming from a service with specific version does not retrieve the associated options via "OptionsApiService" when retrieving the link. The reason is that the recovery code does not remove the '?' character (add in the url to register the version) for to make the match with the "OptionsApiService" service and the match is not done.
- Exemple of WMS: https://servicesvectoriels.atlas.gouv.qc.ca/IDS_GIIN_SW_WMS//service.svc/get?versio=1.1.1
- Exemple IGO link with this wms: `...../?context=_default&zoom=6&center=-71.78933,51.3&invisiblelayers=*&visiblelayers=42ecd6eb-d971-d768-03b0-6d45b2283dc9,a2deb748-a408-66ee-5ce4-def679f5 …
=> fix: url with version on share map link

src/app/pages/portal/portal.component.ts
Default tracking value is only set by storageService
geolocate tracking value can now be set by config ("activateDefault")
```
[ ] Yes
[X] No
```
=> feat(geolocate): add geolocate activateDefault config

angular.json, src/app/pages/portal/portal.component.ts, src/data/geoDataToIDB.json
related to https://github.com/infra-geo-ouverte/igo2-lib/pull/1115
=> feat(geoDB): service to load data from config file into the indexed-db

src/app/app.component.scss
mat-form-field-suffix icon isn't rightly sized
Fix
```
[ ] Yes
[X] No
```
=> fix(mat-form-field-suffix): fix css icon size

src/app/pages/portal/toast-panel/toast-panel.component.ts
When closing the toast panel (query result), the workspace selection was kept.
Clear selection from workspaces
```
[ ] Yes
[x] No
```
=> feat(toast): clear query result trigger workspace clear selection

src/app/pages/portal/portal.component.html, src/app/pages/portal/portal.component.scss, src/app/pages/portal/portal.variables.scss
Due to 16.0.0 changes, the search bar is "jumping" when opening/close the side nav (from menu button)
Impose the position (width) of the searchbar based on portal variables minus 5px.
```
[ ] Yes
[x] No
```
=> fix(portal): search bar position when open/close sidenav

src/app/pages/portal/expansion-panel/expansion-panel.component.ts, src/app/pages/portal/portal.component.html, src/app/pages/portal/portal.component.ts
16.0.0-rc.0 regression fix. 
Maximized workspace display was set to none.
Ensure to have the content of the workspace (expansion panel) show when expanded and maximized.
```
[ ] Yes
[x] No
```
=> refactor(expansionPanel): handle 2 class simultanously base on expansion panel expanded and maximized

docs/_tables/fr/interactiveTour/interactiveTourOptions.csv, docs/interactiveTour_config.rst, src/config/interactiveTour.json
Regression in the interactive tour the placement was broken
https://github.com/infra-geo-ouverte/igo2-lib/issues/1398
=> fix(InteractiveTour): replace deprecated position "auto" by "right"

src/app/pages/portal/map-overlay/map-overlay.enum.ts, src/app/pages/portal/map-overlay/map-overlay.interface.ts
MapOverlay Interface has a property missing.
```
[ ] Yes
[ ] No
```
=> refactor(map-overlay): missing property for MapOverlay Interface

src/config/config.json
At the moment, only one routing source can be used in the Directions tool.
Two sources can now be used. In order to see the toggle to switch between the two, you need:
To be authenticated and authorized to use the second routing source.
Two routing sources that must be provided in the configs.
When the user activates the second/private source a message warns the user.
```
[ ] Yes
[x] No
```
See …
=> feat(directions): added possibility to toggle between two routing sources
