infra-geo-ouverte/igo2

- package.json
- src/css/media.styl
Example of use:
@require '../../css/media.styl';
+media(mobile)
:host 
width: 30%
> mixin stylus for media (mobile)

- src/app/app.component.spec.ts
- src/app/map/shared/map.model.ts
- src/app/map/shared/map.service.spec.ts
- src/polyfills.ts
- src/test.ts
Add types for openlayers and jasmine
> Types openlayers and jasmine

- src/app/app.module.ts
- src/app/core/core.module.ts
- src/app/shared/shared.module.ts
Reverts infra-geo-ouverte/igo2#65
> Revert "refactor(material): move to coreModule"

- src/app/pages/navigator/navigator.component.html
- src/app/pages/navigator/navigator.component.ts
- src/app/shared/flex/flex.component.ts
- src/app/shared/sidenav/sidenav.component.html
> refactor(flex component): Refactor flex component

- src/app/app.store.ts
- src/app/core/context.service.ts
- src/app/core/search.service.ts
- src/app/map/map.component.ts
- src/app/map/shared/layers/layer.ts
- src/app/map/shared/map.ts
- src/app/reducers/available-tools.reducer.ts
- src/app/reducers/map-layers.reducer.ts
- src/app/reducers/map-view.reducer.ts
- src/app/search/adapters/search-adapter-nominatim.ts
- No marker is added
- A marker is added to the map on the focused or selected result.
- The map moves to the focused result but doesn't zoom.
- The map moves and zooms to the selected result.
```
[ ] Yes
[ x ] No
```
> Search result marker

- src/app/pages/navigator/navigator.component.html
- src/app/pages/navigator/navigator.component.styl
- src/app/search/search-bar/search-bar.component.styl
- src/app/search/search-result-details/search-result-details.component.html
- src/app/search/search-result-details/search-result-details.component.spec.ts
- src/app/search/search-result/search-result.component.html
- src/app/search/search-tool/search-tool.component.html
- src/app/search/search-tool/search-tool.component.ts
- src/app/search/sources/search-source-msp.ts
- src/app/shared/collapsible/collapsible.component.html
- src/app/shared/collapsible/collapsible.component.spec.ts
- src/app/shared/collapsible/collapsible.component.styl
- src/app/shared/collapsible/collapsible.component.ts
- src/app/shared/flex/flex.component.html
- src/app/shared/flex/flex.component.styl
- src/app/shared/list/list.component.ts
- src/app/shared/panel/panel.component.html
- src/app/shared/panel/panel.component.styl
- src/app/shared/shared.module.ts
- src/css/styles.styl
- src/css/theme.styl
Search results are not grouped by search source
Search results are grouped by search source and are collapsibles
> feat(group results): Group results by source in a collapsible component

- src/app/core/context.service.ts
- src/app/pages/navigator/navigator.component.html
- src/app/shared/panel/panel.component.styl
- src/css/styles.styl
> fix(ui issue): Fix minor ui issue causing scrollbars to appear

- .angular-cli.json
- src/app/app.component.spec.ts
- src/app/core/context.service.spec.ts
- src/app/core/context.service.ts
- src/app/core/core.module.ts
- src/app/core/logging.service.spec.ts
- src/app/core/logging.service.ts
- src/app/core/request.service.spec.ts
- src/app/core/request.service.ts
- src/app/core/search.service.spec.ts
- src/app/core/search.service.ts
- src/app/core/spinner/spinner.component.spec.ts
- src/app/pages/navigator/navigator.component.spec.ts
- src/app/pages/navigator/navigator.component.ts
- src/app/search/search-bar/search-bar.component.spec.ts
- src/contexts/default.json
- The default context is hardcoded in the context service
- The default context and other contexts are now stored into json files
- Things like ol.Attribution are temporarily not supported in the context.
> feat(context file): Load contexts from json files

- src/app/pages/navigator/navigator.component.html
- src/css/styles.styl
- src/css/theme.styl
- No tooltip
- Tooltip example
```
[ ] Yes
[x] No
```
> feat(tooltip): Tooltip example

- src/app/map/shared/layers/layer-wmts.ts
issue #136 
Plus de zoom. ajout des niveaux 15 à 20
```
[ ] Yes
[x] No
```
> fix(layer-wmts) correction des resolutions

- docs/config_json.rst
- docs/english.rst
> docs(.rst) ajouter json config de contexte

- src/app/app.store.ts
- src/app/context/context-item/context-item.component.html
- src/app/context/context-item/context-item.component.spec.ts
- src/app/context/context-item/context-item.component.ts
- src/app/context/context-tool/context-tool.component.html
- src/app/context/context-tool/context-tool.component.spec.ts
- src/app/context/context-tool/context-tool.component.ts
- src/app/context/context.module.ts
- src/app/context/shared/context.interface.ts
- src/app/context/shared/detailed-context.interface.ts
- src/app/core/context.service.ts
- src/app/core/core.module.ts
- src/app/map/map/map.component.ts
- src/app/map/shared/map.ts
- src/app/pages/navigator/navigator.module.ts
- src/app/reducers/active-context.reducer.ts
- src/app/reducers/contexts-list.reducer.ts
- src/app/reducers/index.ts
- src/app/reducers/map-layers.reducer.ts
- src/app/reducers/map-view.reducer.ts
- src/app/reducers/tools-list.reducer.ts
- src/app/search/search-bar/search-bar.component.ts
- src/app/search/search-tool/search-tool.component.styl
- src/app/shared/list/list.component.ts
- src/app/tool/toolbar/toolbar.component.ts
- src/app/tool/toolbox/toolbox.component.ts
- src/contexts/_contexts.json
- src/contexts/_default.json
- No context tool
- Context tool that allows selecting a context from the list and load it
- Contexts are kept in files
```
[ ] Yes
[x] No
```
> feat(context tool): Basic file based context tool

- docs/config_json.rst
- docs/english.rst
- docs/index.rst
- docs/introduction.rst
- src/assets/locale/en.json
- src/assets/locale/fr.json
> docs(.rst,i18) traduction et documentation

- docs/config_json.rst
- docs/english.rst
- docs/index.rst
- src/contexts/_contexts.json
- src/contexts/qc911.json
> docs(url) et contextes

- src/css/styles.styl
> ui(form): position the submit button at the bottom of the form

- src/app/map/layer-list-item/layer-list-item.component.html
- src/app/map/layer-list-item/layer-list-item.component.spec.ts
- src/app/map/layer-list-item/layer-list-item.component.ts
- src/app/map/layer-list/layer-list.component.html
- src/app/map/map/map.component.ts
- src/app/map/shared/layer.service.ts
- src/app/map/shared/layers/layer-wms.ts
- src/app/map/shared/layers/layer.ts
- src/app/search/search-tool/search-tool.component.html
- src/app/shared/collapsible/collapsible.component.html
- src/app/shared/collapsible/collapsible.component.styl
- src/app/shared/collapsible/collapsible.component.ts
- src/app/shared/list/list-item.directive.ts
- src/app/shared/list/list.component.html
- src/app/shared/list/list.component.styl
- src/app/shared/list/list.component.ts
- src/assets/locale/en.json
- src/assets/locale/fr.json
> feat(layer list): Basic layer list

- src/app/shared/directives/collapse.directive.ts
- src/css/styles.styl
> fix(style): Fix list style

- src/app/context/context-editor/context-editor.component.html
- src/app/context/context-form/context-form.component.html
- src/app/map/layer-editor/layer-editor.component.html
- src/app/map/layer-editor/layer-editor.component.spec.ts
- src/app/map/layer-form/layer-form.component.html
- src/app/map/layer-form/layer-form.component.spec.ts
- src/app/map/layer-form/layer-form.component.ts
- src/app/map/map.module.ts
- src/assets/locale/en.json
- src/assets/locale/fr.json
- src/css/styles.styl
- No layer form
- Dummy layer form that doesn't save
```
[ ] Yes
[x] No
```
> feat(layer): Dummy layer form

- src/app/map/layer-editor/layer-editor.component.spec.ts
- src/app/map/layer-form/layer-form.component.html
- src/app/map/layer-form/layer-form.component.ts
- src/app/map/layer-legend/layer-legend.component.html
- src/app/map/layer-legend/layer-legend.component.spec.ts
- src/app/map/layer-legend/layer-legend.component.styl
- src/app/map/layer-legend/layer-legend.component.ts
- src/app/map/layer-list-item/layer-list-item.component.html
- src/app/map/layer-list-item/layer-list-item.component.spec.ts
- src/app/map/layer-list-item/layer-list-item.component.styl
- src/app/map/layer-list/layer-list.component.spec.ts
- src/app/map/map-editor/map-editor.component.spec.ts
- src/app/map/map.module.ts
- src/app/map/map/map.component.ts
- src/app/map/shared/layers/layer-wms.ts
- src/app/map/shared/layers/layer.ts
- src/app/map/shared/map.ts
- src/app/shared/collapsible/collapsible.component.html
- src/app/shared/collapsible/collapsible.component.styl
- src/assets/locale/en.json
- src/assets/locale/fr.json
- src/contexts/_default.json
- src/contexts/qc911.json
- src/css/styles.styl
- No layer legend
- Base layer legend that supports html and image content
- WMS layer legend (when none is defined in the context) that does "GetLegendGraphic" request for each layer in it's params.
- Legend(s) can also have a title different fro the layer title. In that case, the legend is wrapped into a collapsible element.
```
[ ] Yes
[x] No
```
> layer(legend): Base layer and wms layer legend

- src/app/context/context-list/context-list.component.ts
- src/app/context/shared/context.service.ts
- src/app/core/request.service.ts
- src/app/map/map/map.component.ts
- No message when trying to load an invalid context (invalid json)
- Error message when trying to load an invalid context or whenever a request returns
an invalid json
```
[ ] Yes
[x] No
```
> feat(context): Handle invalid JSON

- e2e/app.e2e-spec.ts
- src/app/map/layer-list-item/layer-list-item.component.html
- src/app/pages/navigator/navigator.component.html
- src/app/pages/navigator/navigator.component.ts
> ui(menu): Make the bottom menu collapsible instead of expandable

- src/app/pages/navigator/navigator.component.html
> ui(scroll): Fix scroll issue

- .travis.yml
> test(e2e): run e2e via npm and output logs

- src/app/tool/toolbox/toolbox.animation.ts
- src/app/tool/toolbox/toolbox.component.html
- src/app/tool/toolbox/toolbox.component.ts
- The current tool slide out then then new tool appear
- The current tool disappear and the new tool slide in
```
[ ] Yes
[x] No
```
> ui(animation): Imrpove animation behavior

- src/app/analysis/time-analyser/time-analyser.component.ts
- src/app/context/context-editor/context-editor.component.ts
- src/app/context/context-list/context-list.component.ts
- src/app/map/layer-editor/layer-editor.component.ts
- src/app/map/map-editor/map-editor.component.ts
- src/app/map/map/map.component.ts
- src/app/map/shared/layers/layer-osm.ts
- src/app/map/shared/layers/layer-vector.ts
- src/app/map/shared/layers/layer-wms.ts
- src/app/map/shared/layers/layer-wmts.ts
- src/app/map/shared/layers/layer-xyz.ts
- src/app/map/shared/layers/layer.ts
- src/app/map/shared/map.ts
- src/app/map/shared/query.service.ts
- src/app/search/search-tool/search-tool.component.ts
- src/app/store/reducers/layers.reducer.ts
- src/app/tool/shared/tool.service.ts
- Options are defined in the tool class
- Options are defined in the register decorator
```
[ ] Yes
[x] No
```
> refactor(tool): Refactor the way tools are registered

- src/app/app.component.spec.ts
> test(app): fix app test

- README.md
- docs/config_json.rst
- docs/english.rst
- docs/global.rst
- src/contexts/embacle.json
> docs (wfs, wmstime) + layer wfs nom + ang4 doc

- .angular-cli.json
- package.json
Manual operation to create release
Auto-generated release
> chore(release): add auto-generated release

- README.md
- docs/config_json.rst
- docs/english.rst
> docs (add new params) :  params layer supported

- src/app/pages/portal/portal.component.ts
Proper enum usage derived from infra-geo-ouverte/igo2-lib#193
```
[ ] Yes
[X] No
```
> Fix overlay action

- src/app/pages/portal/portal.component.html
Changed needed based on PR 198 from infra-geo-ouverte/igo2-lib#198 to provide map to the side-nav
```
[ ] Yes
[ ] No
```
> feat(context) provide map to igo-sidenav

- src/config/config.json
- [X ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
```
[ ] Yes
[X] No
```
> fx(config) Fix config params

- src/app/pages/portal/portal.component.html
- src/config/config.json
- src/contexts/embacle.json
New source for context based on igo2-lib master branch (wms and wfs filterable)
```
[ ] Yes
[ ] No
```
> ui(*) Adding new feature to the demo

- src/contexts/_default.json
- src/contexts/embacle.json
- [X ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
Add options to control searchResults tool (focusFirst)
```
[ ] Yes
[x ] No
```
> ui(*) add options to manage searchResults tool

- proxy.conf.json
- src/app/app.module.ts
- src/config/config.json
Add a new source to demo. 
```
[ ] Yes
[X] No
```
> feat(search-source) provide reseautq to demo, but set to enabled:false

- src/contexts/_default.json
- [X ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
Adding a tool for About the app.
```
[ ] Yes
[X] No
```
> feat(tool) adding a about tool fully customizable by html.

- src/contexts/embacle.json
> ui(*) enabling some tools and options.

- src/contexts/_default.json
- src/contexts/embacle.json
- src/contexts/qc911.json
> Updating demo with igo2-lib params

- package.json
- [x ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
Missing dependencies.
```
[ ] Yes
[x ] No
```
> Cache -- unmet dependencies.

- src/contexts/mapOverlay.json
> Change default baseLayer for demo of mapOverlay

- src/app/pages/portal/portal.component.scss
- src/contexts/mapOverlay.json
> Fix map overlay igo toast

- src/app/pages/portal/map-overlay/map-overlay.component.html
- src/app/pages/portal/map-overlay/map-overlay.interface.ts
- src/contexts/mapOverlay.json
```
[ x ] Yes
[ ] No
```
Context and/or config using the padding parameters of mapOverlay need to be change for margin.
paddingLeft -> marginLeft
paddingRight -> marginRight
paddingTop -> marginTop
paddingBottom -> marginBottom
> Fix map overlay padding click

- src/app/pages/portal/map-overlay/map-overlay.component.ts
> mapOverlay adapt to media change

- src/app/app.component.scss
- src/app/pages/portal/portal.component.ts
- src/contexts/_contexts.json
- src/contexts/message.json
A message can be defined in context and will be shown by the message service when the context is loaded
```
[ ] Yes
[ x ] No
```
> Startup message from context

- package.json
- src/config/config.json
- src/contexts/testForPr294_295_296_297.json
Add some example for catalog & a test context to test some PR from the lib. 
```
[ ] Yes
[x] No
```
> feat(demo) add catalog and a context to validate many PR

- package.json
- src/polyfills.ts
Fix a object issue on IE
```
[ ] Yes
[x] No
```
> Various fixes alpha

- package-lock.json
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.scss
- src/app/pages/portal/portal.component.ts
- src/app/pages/portal/toast-panel/toast-panel.component.ts
Search module adjustment:
- clear feature on research clean button
- geolocate button adjustment for mobile
- queryable layer panel resizem for mobile and landscape
> feat/ui(search): clear feature, geolocate button, queryable layer panel resize

- src/app/pages/portal/portal.component.html
query does not take care of the features already on the map
!query does not take care of the features already on the map
```
[ ] Yes
[x] No
```
> ui(query-feature) enable query on feature presents on the map

- src/app/pages/portal/toast-panel/toast-panel.component.html
- src/app/pages/portal/toast-panel/toast-panel.component.scss
- src/app/pages/portal/toast-panel/toast-panel.component.ts
* swipe removed from desktop media
* label user-select is working in toast-panel content
> fix(toast-panel): label select in toast-panel content is now working

- src/contexts/embacle.json
Moving property to sourceOptions
```
[ ] Yes
[x] No
```
> fix(demo) time filter moved into sourceOptions

- src/app/pages/portal/map-overlay/index.ts
- src/app/pages/portal/map-overlay/map-overlay.component.html
- src/app/pages/portal/map-overlay/map-overlay.component.scss
- src/app/pages/portal/map-overlay/map-overlay.component.ts
- src/app/pages/portal/map-overlay/map-overlay.interface.ts
- src/app/pages/portal/map-overlay/map-overlay.module.ts
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.module.ts
- src/contexts/_contexts.json
- src/contexts/mapOverlay.json
> feat(overlay): add map-overlay

- src/app/pages/portal/expansion-panel/expansion-panel.component.scss
- src/app/pages/portal/portal.animation.ts
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.scss
- src/app/pages/portal/portal.component.ts
- src/app/pages/portal/portal.variables.scss
- src/app/pages/portal/toast-panel/toast-panel.component.html
- src/app/pages/portal/toast-panel/toast-panel.component.scss
All noticed bugs on IE and Firefox (issues #310 and #295) : 
- Firefox --> expansion panel, toast panel, measurer, right click
- IE --> geolocate button, search-bar, baselayers switcher, expansion panel, toast panel
> fix/ui(portal): bugs fixed for Internet Explorer and Mozilla Firefox

- src/app/pages/portal/portal.component.ts
Show coordinates on Internet Explorer = NaN, NaN
Window.scrollY and Window.scrollX are note supporter by IE.
[https://developer.mozilla.org/fr/docs/Web/API/Window/scrollY](https://developer.mozilla.org/fr/docs/Web/API/Window/scrollY)
```
[ ] Yes
[x] No
```
> Show coordinates on Internet Explorer = NaN, NaN

- src/app/pages/portal/portal.component.ts
> Unsubscribe to addlayers

- src/app/pages/portal/portal.component.ts
> refactor(portal) filter the search source by term or reverse

- src/polyfills.ts
Query crash on IE due to matchAll not found
"L’objet ne gère pas la propriété ou la méthode « matchAll »" 
```
[ ] Yes
[ ] No
```
> polyfills(queryService) Matchall polyfill

- package.json
linked to https://github.com/infra-geo-ouverte/igo2-lib/pull/444
linked to https://github.com/infra-geo-ouverte/igo2-lib/pull/444
```
[ ] Yes
[x] No
```
> voir https://github.com/infra-geo-ouverte/igo2-lib/pull/444

- src/contexts/ogcFilters.json
Refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/504
Refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/504
```
[ ] Yes
[x] No
```
> refactor pushbuttons structure based on PR IGO2-lib #504

- README.md
> refactor(readme) - update version

- src/app/pages/portal/portal.component.ts
Layers added from URL were not interpreting the visibility param from url.
```
[ ] Yes
[x] No
```
> Layers added by url now correctly interpret the visibility param from url

- src/app/pages/portal/portal.component.ts
> fix(portal): WMS URL params bug fix

- src/environments/environment.github.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/529
> Coord conversion

- src/app/app.component.scss
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.ts
- src/environments/environment.github.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
REFER TO https://github.com/infra-geo-ouverte/igo2-lib/pull/537
```
[ ] Yes
[x] No
```
> Pointer move

- src/app/pages/portal/portal.component.ts
Wrong method name.
```
[ ] Yes
[x] No
```
> refactor(portal) method name for enable pointer summary

- src/app/pages/portal/toast-panel/toast-panel.component.ts
Low emphasis on selected feature
```
[ ] Yes
[x] No
```
> Selected feature stroke width is now doubled (PR igo2-lib #556)

- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.ts
- Manage search settings change to fix display more results
> fix(search-results): display more results fix

- src/contexts/ogcFilters.json
> wfs oufput in this geojson do not have crs property

- src/app/app.module.ts
refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/578
```
[ ] Yes
[ ] No
```
> refactor(routing) renaming routing to directions

- .readthedocs.yml
- docs/_static/custom.css
- docs/conf.py
> docs(configuration) Bypass page max-width by css

- docs/config_json.rst
- proxy.conf.json
- src/app/app.module.ts
- src/environments/environment.ts
https://github.com/infra-geo-ouverte/igo2-lib/pull/583
> feat(datasource): Provide options service

- src/app/pages/portal/portal.component.ts
- src/app/pages/portal/sidenav/sidenav.component.ts
Current behavior : When you enter a certain catalog, tool title is "Catalog"
New behavior : tool title is now the Catalog title
Issue #461 of igo-lib
> Catalog browser title

- src/app/pages/portal/portal.component.html
What is the current behavior? (You can also link to an open issue here)
Refer to infra-geo-ouverte/igo2#422
What is the new behavior?
Fix infra-geo-ouverte/igo2#422
```
[ ] Yes
[x] No
```
> On uncheck, last checked source stay in search-results

- docs/config_json.rst
DOC update based on 
**https://github.com/infra-geo-ouverte/igo2-lib/pull/603**
```
[ ] Yes
[x] No
```
> doc(import) configurable file size on import

- src/app/pages/portal/portal.component.ts
- src/contexts/ogcFilters.json
refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/608
> Ogc filter operators

- docs/properties.rst
- package-lock.json
- [ x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
Correction of level in table of content
french fault
```
[ ] Yes
[x ] No
```
> Docs(*) - Correction TOC level

- src/app/pages/portal/toast-panel/toast-panel.component.ts
Zoom auto apply only when zoom auto is checked and not on selected result
> fix(query): zoom auto on single query feature

- docs/properties.rst
- [ x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
fix doc error and level of TOC 
```
[ ] Yes
[x ] No
```
> docs(*): fix error maxZoomOnExtent and level of table of content

- docs/config_json.rst
- docs/index.rst
- docs/properties.rst
- src/app/pages/portal/portal.component.ts
- src/app/pages/portal/sidenav/sidenav.component.ts
- src/config/config.json
- src/contexts/_base.json
- src/contexts/ogcFilters.json
- src/contexts/timeFilter.json
Related to https://github.com/infra-geo-ouverte/igo2-lib/pull/625
```
[x] Yes
[x] No
```
> Enhanced table of content for layers management

- docs/config_json.rst
- src/app/pages/portal/toast-panel/toast-panel.component.ts
> Import export naming

- docs/properties.rst
Wrong title and 2 properties missing.
```
[ ] Yes
[x] No
```
> doc(sourceFields) Update sourceFields properties

- src/app/pages/portal/portal.component.ts
- The wmts registered in the url (coming from a link sharing) are not integrated into the map.
- The wmts registered in the url (coming from a link sharing) are integrated into the map.
refer to issues infra-geo-ouverte/igo2-lib#670
prerequies: pullRequest infra-geo-ouverte/igo2-lib#671
> * (feat): Add copy link for WMTS

- package-lock.json
- package.json
- src/app/pages/portal/portal.component.ts
- Add turf point-on-feature tool from library
- Adjust google maps link
> add turf point on feature

- src/app/app.module.ts
- src/config/config.json
- src/environments/environment.github.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- Allow cadastre search source to be used in the search bar settings
> Cadastre provider

- docs/url_control.rst
- src/app/pages/portal/portal.component.ts
- Allow the user to add layer by URL file from query params
- Test has been done with geojson file from Données Québec
> feat(query-params): add layer by url (données Québec)

- docs/config_json.rst
- docs/index.rst
- docs/interactiveTour_config.rst
- package-lock.json
- package.json
- src/app/app.component.ts
- src/app/pages/portal/portal.component.scss
- src/app/pages/portal/portal.component.ts
- src/app/pages/portal/portal.module.ts
- src/app/pages/portal/portal.theming.scss
- src/app/pages/portal/sidenav/sidenav.component.html
- src/app/pages/portal/sidenav/sidenav.module.ts
- src/app/pages/portal/toast-panel/toast-panel.component.html
- src/app/pages/portal/welcome-window/welcome-window.component.html
- src/app/pages/portal/welcome-window/welcome-window.component.scss
- src/app/pages/portal/welcome-window/welcome-window.component.spec.ts
- src/app/pages/portal/welcome-window/welcome-window.component.ts
- src/app/pages/portal/welcome-window/welcome-window.module.ts
- src/app/pages/portal/welcome-window/welcome-window.service.spec.ts
- src/app/pages/portal/welcome-window/welcome-window.service.ts
- src/app/pages/portal/welcome-window/welcome-window.theming.scss
- src/config/config.json
- src/config/interactiveTour.json
- src/environments/environment.github.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/locale/en.json
- src/locale/fr.json
- src/styles.scss
- [x ] Docs have been added / updated (for bug fixes / features)
[https://github.com/infra-geo-ouverte/igo2/issues/382](url)
igo2#382
The pilote can now config interactive tour and a welcomeWindow to present the app.
Many tours can be configure on tool and a general tour.
see the doc to know how to config.
```
[ ] Yes
[x ] No
```
> feat(interactiveTour + welcomeWindows+docs) add new component, config and doc

- docs/config_json.rst
- docs/interactiveTour_config.rst
- docs/properties.rst
add docs for legendOptions{}
fix exemple for interactiveTour
> (docs) add legend option+ fix config interactive tour

- docs/url_control.rst
- Fix Url control documentation for vector parameter
> fix(docs): fix url control vector docs

- src/config/interactiveTour.json
- Fix interactive tour global condition on menu button (ng-reflect attribute can't be used in production mode)
> Fix interactive tour global

- src/config/interactiveTour.json
- Fix last ng-reflect attribute selector (can't use in production environment)
> fix last ng-reflect attribute

- src/contexts/testExport.json
> fix(demo) urls

- src/app/app.component.ts
- src/app/pages/portal/welcome-window/welcome-window.component.html
- src/app/pages/portal/welcome-window/welcome-window.component.ts
- src/config/config.json
The app title for Discover IGO is not customizable.
Now it is. 
Linked with https://github.com/infra-geo-ouverte/igo2-lib/pull/741
**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**
> Discover IGO - Customizable title

- src/app/pages/portal/welcome-window/welcome-window.component.html
- src/app/pages/portal/welcome-window/welcome-window.component.ts
Bug, translation service not injected.
Fix it. 
```
[ ] Yes
[x] No
```
> fix(welcome-window) translation injection not done yet

- docs/config_json.rst
- src/app/pages/portal/welcome-window/welcome-window.service.ts
- src/config/config.json
Add a param in config.json to set the number of time you want to show the welcome window
If you want the welcome window to pop just 1 or 2 time just set that param.
"welcomeWindow": {
"nbVisitToShow": 2,
}
> feat(Welcome window) add param nbVisitToShow

- docs/url_control.rst
> docs(search) ajout de hastag possible

- docs/config_json.rst
the resume tab doesn't appear in doc
fix
> Fix(docs) config resume

- src/app/pages/portal/portal.component.ts
The emphasis feature need to monitor the selected feature.. to be deleted on result clear. 
```
[ ] Yes
[x] No
```
> feat(search-result) clear selected feature to clear feature emphasis

- docs/config_json.rst
- docs/interactiveTour_config.rst
- docs/properties.rst
fix and feat documentation.
Bad link, line-block, add some param
> fix(docs) Documentation

- src/app/pages/portal/toast-panel/toast-panel.component.html
- src/app/pages/portal/toast-panel/toast-panel.component.ts
- src/app/pages/portal/toast-panel/toast-panel.module.ts
- src/contexts/_contexts.json
- src/contexts/variousFormats.json
- src/locale/en.json
- src/locale/fr.json
1- more example
2-Add a warning icon/tooltip if the selected result is out of the current view.
```
[ ] Yes
[x] No
```
> Add a warning icon/tooltip if the selected result is out of the current view.

- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.scss
- src/app/pages/portal/portal.component.ts
- src/locale/en.json
- src/locale/fr.json
If the source layer for a workspace is out of range, the data is still shown into the workspace.
Workspace - The workspace is not available at this resolution 
```
[ ] Yes
[x] No
```
>  Workspace - The workspace is not available at this resolution

- package-lock.json
- package.json
> add turf/buffer to packages

- .gitignore
- docs/.rstcheck.cfg
- docs/config_json.rst
- docs/properties.rst
- docs/shortcut.rst
- docs/todo.rst
- src/contexts/layerSync.json
- src/contexts/ogcFilters.json
- src/contexts/testExport.json
- src/contexts/variousFormats.json
- src/contexts/workspace.json
- src/environments/environment.ts
Fixes and enhancements  in the documentation.
Addition of some extra examples in contexts.
```
[ ] Yes
[x] No
```
> Documentation fix and enhancement

- docs/properties.rst
- src/contexts/_base.json
- src/locale/en.json
refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/775
> docs(import-export-tool) provide options to control which type is allowed and which type is open by default

- src/app/pages/portal/portal.component.ts
…tionsApi (if enabled)
Shared layers do not retrieve their options from the optionsApi
Shared layers now can retrieve their options from the optionsApi.
```
[ ] Yes
[x] No
```
> feat(portal) shared layers now can retrieve their options from the optionsApi

- .github/workflows/codeql-analysis.yml
> chore(code-analysis): Create codeql-analysis.yml

- docs/properties.rst
refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/800
> Doc - Contextual legend

- src/contexts/_base.json
layer name has changed.
```
[ ] Yes
[ ] No
```
> refactor(demo) layer name change

- docs/properties.rst
- src/contexts/ogcFilters.json
- src/contexts/variousFormats.json
ajout d'un id dans le context de divers format pour les types vector pour permettre que le partage de carte fonctionne bien avec ces sources
> feat(docs+exemple) id for shareMap - vector

- docs/config_json.rst
- docs/properties.rst
- src/environments/environment.ts
related to https://github.com/infra-geo-ouverte/igo2-lib/pull/811
> Esri image

- src/contexts/testExport.json
lié a https://github.com/infra-geo-ouverte/igo2-lib/pull/814
> Export format, restricted list by layer, examples

- src/config/interactiveTour.json
the select multiple mode stay checked on tour. 
uncheck it.
```
[ ] Yes
[x] No
```
> fix(interactiveTour) uncheck the select multiple option on tour.

- src/app/pages/portal/toast-panel/toast-panel.component.html
add button resize window on list result
```
[ ] Yes
[ x] No
```
> Fix(toast panel) add resize button in list result

- docs/config_json.rst
- docs/properties.rst
- Add documentation for ogcFilter reshuffle (checkboxes, radioButtons, calendar...)
- Add documentation for the depot-api config (necessary to add training guides)
> docs(ogcFilter/depotConfig)

- docs/config_json.rst
- docs/properties.rst
- src/contexts/_base.json
- src/environments/environment.ts
related to https://github.com/infra-geo-ouverte/igo2-lib/pull/835
> feat(demo): external provider for catalog

- src/app/pages/portal/portal.component.ts
based on https://github.com/infra-geo-ouverte/igo2-lib/pull/838
> Multiple search refactor

- docs/config_json.rst
refer to https://github.com/infra-geo-ouverte/igo2-lib/pull/839
> doc(message): add the date range to message doc.

- src/contexts/layerSync.json
- src/contexts/ogcFilters.json
- src/contexts/workspace.json
> fix(demo): wrong properties

- docs/properties.rst
- src/config/config.json
fix docs layer property and workspace duplicate
add exemple stored query in docs
add storedqueries search config in demo
> feat-fix(Docs) add storedqueries mffp exemple doc + demo - fix layer property - fix workspace duplicate

- src/app/pages/portal/portal.component.ts
> fix(welcomewindow): trigger the welcome window if no auth url defined

- src/config/config.json
- src/environments/environment.prod.ts
Delete cadastre search source from config
```
[X] Yes
[ ] No
```
> fix(cadastre): delete cadastre search source

- src/contexts/_base.json
Add OSM humanitarian baselayers in the baselayer's list
> add OSM - humanitaire in use case baselayers

- docs/properties.rst
- src/contexts/_base.json
The current behavior is no documentation available for the controls options in the map options.
Gives the users the documentation for the controls options in the map options. And an example in the context.
```
[ ] Yes
[x] No
```
> Scale bar doc

- docs/config_json.rst
broken doc section 
```
[ ] Yes
[ ] No
```
> fix(doc): missing example for overlaystyle

- docs/properties.rst
- src/contexts/ogcFilters.json
> docs(ogcFilter): added docs for MatSelect selector and example in ogcFilters.json

- src/style/theme.scss
feat(style/theme): added a new theme call bluedq
> feat(style/theme): added a new theme call bluedq

- src/app/pages/portal/portal.component.html
- src/contexts/_base.json
- [x ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
**What is the current behavior?** 
no advanced tools in IGO
2 tools added: swipe and coordinates. With the first we are able to compare the layers, the second let use the coordinates of center of the map in different projections
```
[ ] Yes
[x ] No
```
> feat(map): Advanced tools

- src/contexts/messages.json
related to https://github.com/infra-geo-ouverte/igo2-lib/pull/943
> feat(messages): a message is always show when the layer become visible

- docs/_tables/fr/config/welcomeWindow.csv
- docs/config_json.rst
- src/app/pages/portal/portal.component.ts
- src/app/pages/portal/welcome-window/welcome-window.component.ts
fix(tour): when the tool was activated by url, the wrong tour was used.
Before activate a tool by url, wait for the welcome window to be closed. 
```
[ ] Yes
[ ] No
```
> fix(tour): when the tool was activated by url, the wrong tour was used.

- docs/_tables/fr/properties/sources/mvt.csv
- docs/_tables/fr/properties/sources/wms.csv
```
[ ] Yes
[x] No
```
https://github.com/infra-geo-ouverte/igo2-lib/pull/927
> ajout de la doc du PR-927

- docs/_tables/fr/properties/sources/mvt.csv
- docs/_tables/fr/properties/sources/wms.csv
```
[ ] Yes
[X] No
```
Same as https://github.com/infra-geo-ouverte/igo2/pull/693. It was merged with "master" at first, now with "next". @matrottier
> docs(wms/mvt): add custom query url docs

- src/app/pages/portal/toast-panel/toast-panel.component.ts
ctrl-c do not work
allow ctrl-c to copy content
```
[ ] Yes
[x] No
```
> fix(toast): allow ctrl-c to copy content

- src/contexts/_default.json
lié a https://github.com/infra-geo-ouverte/igo2-lib/pull/963
> demo(default): add an example for html query with querytitle

- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.ts
- src/config/config.json
N/A
Two new configs have been added (will be used eventually for simplified/integrated version of IGO2)
- showMenuButton: Allows to show/hide the menu button.
- showSearchBar: Allows to show/hide search bar. 
> feat(portal): new configs showMenuButton and showSearchBar

- README.md
Add wiki link and gitter badge
> chore(readme): ajustement readme pour gitter et wiki de contribution

- docs/_tables/fr/properties/sources/wms.csv
- docs/_tables/fr/properties/workspaceOptions.csv
- docs/properties.rst
- src/app/pages/portal/portal.component.ts
- src/contexts/workspace.json
** need to be integrate with PR in LIBS: 
https://github.com/infra-geo-ouverte/igo2-lib/pull/995
new query behavior: WFS and workspace/table attributaire
```
[ ] Yes
[ x] No
```
> feat(portal) Wks new query behavior

- src/app/pages/portal/portal.component.ts
Error on search bar initialization
Fix it.
```
[ ] Yes
[ ] No
```
> fix(portal): missing searchbar

- docs/properties.rst
> docs(properties): add map home extent docs

- src/contexts/layerSync.json
- src/contexts/variousStyles.json
> Label resolution

- docs/_tables/fr/properties/tools/searchResultsOptions.csv
- docs/properties.rst
> docs(search-results): top panel default state

- docs/_tables/fr/config/config-summary.csv
- docs/config_json.rst
- src/config/config.json
relié a https://github.com/infra-geo-ouverte/igo2-lib/pull/1037
> feat(*): favorite context for non authenticated user (local storage)

- src/app/app.component.scss
Spinner is punctually not showing (on query or display layer)
Spinner works correctly
```
[ ] Yes
[X] No
```
> fix(spinner): fix ponctual spinner display problems

- src/app/pages/portal/portal.component.ts
Simple refactor to handle easily local actions in my local branch ;) 
Simple refactor to handle easily local actions in my local branch ;) 
```
[ ] Yes
[x] No
```
> refactor(portal): simple refactor to handle action in const

- docs/_tables/fr/config/catalog.csv
- docs/config_json.rst
- src/app/pages/portal/portal.component.scss
- src/environments/environment.ts
Documentation doesn't cover the new Forced Metadata feature
Documentation and examples are now provided in ReadTheDocs
```
[ ] Yes
[x] No
```
> docs(geo): Forced Metadata documentation and examples

- angular.json
- X ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
App does not consider node_modules changes on ng serve command and does not live reloading
App does consider node_modules changes on ng serve command
But still does not update on live reloading
```
[ ] Yes
[X] No
```
> fix(dev-serve): fix enabled cache on ng serve

- .github/workflows/codeql-analysis.yml
https://github.com/infra-geo-ouverte/igo2-lib/pull/1099
> chore(codeql): Move to codeql v2 (issue 1071)

- .github/workflows/onPush.js.yml
ghactions only test node 14
add node 16
```
[ ] Yes
[x] No
```
> chore(gh-actions): add node 16

- package.json
> chore(package): author update

- docs/_tables/fr/properties/layer.csv
docs for new layer param notShowOptionButtonZoomToExtent
> feat(Doc)layer param not show option button zoom to extent (pr1136)

- docs/config_json.rst
> docs(geolocate): add geolocate options docs

- angular.json
[chore(angular): use igo2/common assets](https://github.com/infra-geo-ouverte/igo2/commit/37fe9ee41073a1b65eec61b79fa4f7de35187f15)
related to https://github.com/infra-geo-ouverte/igo2-lib/pull/1118
> chore(angular): use igo2/common assets

- package-lock.json
- package.json
> feat(core): upgrade ngx-color-picker to 13

- src/app/pages/portal/portal.component.html
Context menu on ios doesn't work well
map-browser now use the long press directive for context menu
link to : https://github.com/infra-geo-ouverte/igo2-lib/pull/1119
```
[ ] Yes
[X] No
```
> feat(map-browser): add longpress directive

- .github/workflows/gh-release.yml
chore(gh-actions): adjust gh release action to zip only files, not parent directory
> chore(gh-actions): adjust gh release action to zip only files, not parent directory

- src/contexts/messages.json
- src/styles.scss
https://github.com/infra-geo-ouverte/igo2/issues/860
> fix(message-class custom) <a> class with underline blue

- docs/_tables/fr/config/import-export.csv
- docs/config_json.rst
- src/app/pages/portal/portal.component.ts
- src/environments/environment.github.ts
- src/environments/environment.ts
…wnloading data to indexeddb
No possibility to configurate the data download into the indexeddb.
Setup a config.
https://github.com/infra-geo-ouverte/igo2-lib/pull/1133 
```
[ ] Yes
[ ] No
```
> Idb config

- src/app/pages/portal/portal.component.ts
When ilayer respond too fast for icherche call, sf parameter select the first ilayer search results
Adjust delay to allow icherche search result to fill the entity store
```
[ ] Yes
[X] No
```
> fix(portal): fix search sf params

- docs/config_json.rst
- src/environments/environment.ts
DOC
DOC
```
[ ] Yes
[x] No
```
> docs(storageOptions): add doc and example for storageoptions

- .github/workflows/gh-release.yml
Zip build was not including sub folder content.
Fix it.
```
[ ] Yes
[ ] No
```
> fix(gh-release): github action for zipped build

- docs/_tables/fr/config/config-summary.csv
- docs/_tables/fr/config/search-bar.csv
- docs/config_json.rst
- src/app/pages/portal/portal.component.ts
- src/config/config.json
N/A
Added docs and new config
```
[ ] Yes
[x] No
```
See https://github.com/infra-geo-ouverte/igo2-lib/pull/1164
> docs(search-bar): switched from input to config for search button

- docs/_tables/fr/config/search-sources-prop.csv
- docs/_tables/fr/config/search-sources.csv
- docs/config_json.rst
- src/config/config.json
N/A
documentation to be considered
```
[ ] Yes
[x] No
```
N/A
> Doc search remove the number of results829 1157

- src/app/pages/portal/portal.component.ts
Unused code.
Delete it.
```
[ ] Yes
[x] No
```
> chore(portal): deletion unused code

- src/app/pages/portal/portal.component.ts
- src/app/services/pwa.service.ts
- src/environments/environment.ts
> fix(pwa): prevent multiple confirm dialog to reload app

- src/app/pages/portal/portal.component.ts
- src/config/config.json
related to https://github.com/infra-geo-ouverte/igo2-lib/pull/1214
> refactor(wake-lock-button): method to control if present of not

- src/app/app.component.ts
- src/app/app.module.ts
- src/app/services/pwa.service.ts
Sometime, translation are not loaded.
Refactor the app_initializer to strictly handle translations instead of the pwa service. PWA reload has been refactored. 
```
[ ] Yes
[x] No
```
> Translations not loaded

- docs/properties.rst
- src/contexts/variousFormats.json
https://github.com/infra-geo-ouverte/igo2-lib/pull/1231
> feat(vector): preload data despite visibiliy or resolution range

- src/app/pages/portal/toast-panel/toast-panel.component.html
- src/app/pages/portal/toast-panel/toast-panel.component.ts
- src/config/config.json
https://github.com/infra-geo-ouverte/igo2-lib/pull/1126
```
[ ] Yes
[ ] No
```
> Geo properties - detect wms properties to add remove layer

- .github/workflows/gh-release.yml
- package-lock.json
- package.json
Current changelog was not applied.
Now it is.
```
[ ] Yes
[x] No
```
> chore(workflows): update gh_release action

- src/config/interactiveTour.json
https://github.com/infra-geo-ouverte/igo2/issues/1054
Linked PR: https://github.com/infra-geo-ouverte/igo2-lib/pull/1457
> fix(InteractiveTour): add the auto placement

- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.scss
- src/app/pages/portal/portal.variables.scss
- src/app/pages/portal/sidenav/sidenav.component.scss
https://github.com/infra-geo-ouverte/igo2/issues/1062
> fix(portal): remove spacer when sidebar is open

- src/app/pages/portal/toast-panel/toast-panel.component.scss
- src/environments/environment.ts
this behavior related to #1061 
```
[ ] Yes
[ ] No
```
> style(toast-panel): fix full extent get info

- docs/properties.rst
- src/contexts/variousFormats.json
- src/contexts/variousStyles.json
- src/data/geoDataToIDB.json
THe previous fire hydrant src was not available anymore.
Replace it by a new source.
```
[ ] Yes
[x] No
```
> feat(demo): source change for fire hydrant from Donnees Quebec

- proxy.conf.json
- src/app/app.theme.scss
- src/app/pages/portal/expansion-panel/expansion-panel-button/expansion-panel-button.component.html
- src/app/pages/portal/expansion-panel/expansion-panel-button/expansion-panel-button.component.scss
- src/app/pages/portal/expansion-panel/expansion-panel-button/expansion-panel-button.component.spec.ts
- src/app/pages/portal/expansion-panel/expansion-panel-button/expansion-panel-button.component.ts
- src/app/pages/portal/expansion-panel/expansion-panel-button/expansion-panel-button.theme.scss
- src/app/pages/portal/expansion-panel/expansion-panel-header.component.html
- src/app/pages/portal/expansion-panel/expansion-panel-header.component.scss
- src/app/pages/portal/expansion-panel/expansion-panel-header.component.ts
- src/app/pages/portal/expansion-panel/expansion-panel.module.ts
- src/app/pages/portal/portal-theme.scss
- src/app/pages/portal/portal.animation.ts
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.scss
- src/app/pages/portal/portal.component.ts
- src/style/breakpoints.scss
- src/style/theme.scss
this behavior related to [#1500](https://github.com/infra-geo-ouverte/igo2-lib/issues/1500)
Linked PR: https://github.com/infra-geo-ouverte/igo2-lib/pull/1505
> fix(geo): replace tablet view by medium and small screen

- proxy.conf.json
- src/environments/environment.github.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
this behavior related to #1100 
```
[ ] Yes
[ ] No
```
> fix(environment): change focus color

- src/app/pages/portal/expansion-panel/expansion-panel-button/expansion-panel-button.theme.scss
- src/app/pages/portal/portal-theme.scss
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.scss
- src/style/theme.scss
this behavior related to #1112 
```
[ ] Yes
[ ] No
```
> style(expansion-panel-button): solve button width issue

- docs/_tables/fr/properties/linkedLayersOptions.csv
N/A
See https://github.com/infra-geo-ouverte/igo2-lib/pull/1560
```
[ ] Yes
[x] No
```
> docs(linked-layers): Added new config for visibility in Base Layer Switcher

- docs/_tables/fr/config/directions-profile-auth.csv
- docs/_tables/fr/config/directions-profile.csv
- docs/_tables/fr/config/directions.csv
- docs/config_json.rst
N/A
See https://github.com/infra-geo-ouverte/igo2/pull/1150
```
[ ] Yes
[x] No
```
> docs(directions): added possibility to toggle between two routing sources

- src/app/pages/portal/portal.component.ts
- src/app/pages/portal/portal.module.ts
Linked PR: https://github.com/infra-geo-ouverte/igo2-lib/pull/1669
> fix: provider import for @igo2/geo Direction and Search

- src/app/pages/portal/toast-panel/toast-panel.component.ts
These icons were based on SVG icons (MDI)
Find alternative in google font icons
```
[ ] Yes
[x] No
```
> fix(toast): find alternative icons in google font icons

- src/app/pages/portal/portal.component.ts
- src/environments/environment.ts
- src/main.ts
Certaine application n'utilise pas les capacités de offline et on a aucun moyen de désactiver l'instanciation de la base de donnée IndexedDB. Cela nous causait des erreurs dans nos applications alors on propose une manière de désactiver les environnements.
En lien avec:
https://github.com/infra-geo-ouverte/igo2-lib/pull/1700
> Add the possibility to configure the offline capabilities

- src/main.ts
> fix(core): language add static/async loader

- package-lock.json
- src/app/pages/portal/portal.component.html
- src/app/pages/portal/portal.component.ts
- src/app/pages/portal/sidenav/sidenav.component.ts
- src/app/pages/portal/toast-panel/toast-panel.component.ts
- src/contexts/_contexts.json
- src/contexts/layerGroup.json
- src/environments/environment.ts
- src/index.html
- src/styles.scss
À tester avec cette branche de la lib
https://github.com/infra-geo-ouverte/igo2-lib/pull/1697/files
Pour tester, à partir du gestionnaire de couches, vous pouvez créer un groupe via le boutojn ajouter dans le bandeau supérieur du panneau. Il est aussi possible de déplacer les couches via le drag and drop.
> Feature: implement the new layer group structure

- src/app/app.config.ts
- src/main.ts
Angular on changé leur manière d'assembler leurs applications. Il conseil de mettre la configuration dans un fichier app.config
> refactor: use the app config

- src/app/pages/portal/portal.component.html
- src/environments/environment.ts
- src/environments/environnement.interface.ts
Tester avec https://github.com/infra-geo-ouverte/igo2-lib/pull/1754
> Button default options v2
